package models;

import java.util.ArrayList;

/**
 * Model for a recipe.
 * <p/>
 * Created by Jack on 4/4/2015.
 */
public class Recipe {

  /** The recipe ID. */
  private long id;
  /** The name of the recipe. */
  private String name;
  /** A brief description of the recipe. */
  private String description;
  /** The list of ingredients. */
  private ArrayList<Ingredient> ingredientList;
  /** The steps to make the dish. */
  private ArrayList<String> procedure;
  /** The image file name. */
  private String imagePath = "images/kaluaPorkWithKale.jpg";


  /**
   * Creates a recipe object.
   * @param id             The ID of the recipe.
   * @param name           The name of the recipe.
   * @param description    The description of the recipe.
   * @param ingredientList The list of ingredients needed for the recipe.
   * @param procedure      The directions to create the recipe.
   * @param imagePath      The file name for the image. Defaults to place holder image.
   */
  public Recipe(long id, String name, String description, ArrayList<Ingredient> ingredientList, ArrayList<String> procedure, String imagePath) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.ingredientList = ingredientList;
    this.procedure = procedure;
    this.imagePath = imagePath;
  }

  /**
   * Gets te name of the recipe.
   *
   * @return The name.
   */
  public String getName() {
    return name;
  }

  /**
   * Gets the description of the recipe.
   * @return The description.
   */
  public String getDescription() {
    return description;
  }

  /**
   * Gets the list of incidents of the recipe.
   *
   * @return The list of ingredients.
   */
  public ArrayList<Ingredient> getIngredientList() {
    return ingredientList;
  }

  /**
   * Gets the directions to cook the recipe.
   *
   * @return The procedure.
   */
  public ArrayList<String> getProcedure() {
    return procedure;
  }

  /**
   * Gets the file name for the image.
   * @return The image.
   */
  public String getImagePath() {
    return imagePath;
  }

  /**
   * Gets the id.
   * @return The id.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the ID for the recipe. This value is generated by the RecipeDB.add function.
   * @param id the id.
   */
  public void setId(long id) {
    this.id = id;
  }
}
